version: 1.0.{build}

image: Visual Studio 2019

branches:
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Ignore testing a commit if only .md files or assets have changed
# Or if various strings are found in the commit message: updated readme, update readme, update docs, update version, update appveyor
skip_commits:
  files:
    - appveyor.yml
    - '**/*.md'
    - TestScripts/*.txt

  message: /updated readme.*|update readme.*|update docs.*|update version.*|update appveyor.*/

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:

- cmd: >-

    dotnet restore

    dotnet publish ./Wr.ToyRobot.ConsoleApp/Wr.ToyRobot.ConsoleApp.csproj -f netcoreapp3.1 -r win-x64 -c Release --self-contained -o artifacts/win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true

    7z a toyrobot-%APPVEYOR_BUILD_VERSION%-win-x64.zip %APPVEYOR_BUILD_FOLDER%\artifacts\win-x64\*.*

    dotnet publish ./Wr.ToyRobot.ConsoleApp/Wr.ToyRobot.ConsoleApp.csproj -f netcoreapp3.1 -r osx-x64 -c Release --self-contained -o artifacts/osx-x64 /p:PublishTrimmed=true /p:PublishReadyToRun=false

    7z a toyrobot-%APPVEYOR_BUILD_VERSION%-osx-x64.zip %APPVEYOR_BUILD_FOLDER%\artifacts\osx-x64\*.*

    dotnet publish ./Wr.ToyRobot.ConsoleApp/Wr.ToyRobot.ConsoleApp.csproj -f netcoreapp3.1 -r linux-x64 -c Release --self-contained -o artifacts/linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true

    7z a toyrobot-%APPVEYOR_BUILD_VERSION%-linux-x64.zip %APPVEYOR_BUILD_FOLDER%\artifacts\linux-x64\*.*

artifacts:
- path: toyrobot-$(appveyor_build_version)-win-x64.zip
  name: win-x64
- path: toyrobot-$(appveyor_build_version)-osx-x64.zip
  name: osx-x64
- path: toyrobot-$(appveyor_build_version)-linux-x64.zip
  name: linux-x64

deploy:
   # GitHub Deployment for releases
  - provider: GitHub
    repository: willroscoe/Wr.ToyRobot
    tag: $(appveyor_build_version)
    release: ToyRobot $(appveyor_build_version)
    description: 'Initial release'
    auth_token:
      secure: 9JsyY72D34T18UiX5d44wy+AmN+aHYfRGdMkwCTCVpB95mMn1tWQQJ5win8NqrEB
    artifact: /.*\.zip/         # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master